name: Test, build and deploy
on:
  push:

permissions:
  checks: write
  contents: write

jobs: 
  lint: 
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - name: Run lint
        uses: wearerequired/lint-action@v2
        with: 
          auto_fix: true
          eslint: true
          eslint_extensions: ts,js
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm test -- --coverage --ci
      - uses: codecov/codecov-action@v2
  deploy: 
    needs: ['test', 'lint']
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run deploy

